services:
  - type: web
    name: fleetgo-website
    env: static
    buildCommand: pnpm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PNPM_FLAGS
        value: "--no-frozen-lockfile"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
